---
title: "@"
timezone: Europe/Stockholm
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: posts
    output: true
email: mauricio_dot_esguerra@gmail_dot_com
description: General scientific ramblings rooting mainly for biopolymers. My long
  love story as a computational chemist trying to understand RNA, DNA, Proteins (GPCR's,
  Kinases, Enzymes, Medical Targets) and even non-polymeric small molecules. With
  specific stories on the practical day-to-day use of current computational tips and
  tricks.
baseurl: 
url: https://blog.mesguerra.org
github_username: esguerra
remote_theme: pages-themes/midnightt
plugins:
- jekyll-remote-theme
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
permalink: "/:year/:month/:day/:title/"
paginate_path: "/posts/:num/"
paginate: 10
