---
title: blog.mesguerra.org
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mauricio_dot_esguerra@gmail_dot_com
description: Ramblings on biopolymers. My long love story as a computational chemistry with RNA,
DNA, GPCR's, and even non-polymeric small molecules. Some stories on the practical day-to-day
use of current computational tips and tricks.
baseurl: 
url: http://blog.mesguerra.org
github_username: esguerra
remote_theme: yous/whiteglass
plugins:
- jekyll-archives
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
permalink: "/:year/:month/:day/:title/"
paginate_path: "/posts/:num/"
paginate: 5
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: category_archives
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
