---
title: "@"
timezone: Europe/Stockholm
collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: posts
    output: true
email: mauricio_dot_esguerra@gmail_dot_com
description: Ramblings on biopolymers. My long love story as a computational chemist
  trying to understand RNA, DNA, GPCR's, and even non-polymeric small molecules. Also
  some stories on the practical day-to-day use of current computational tips and tricks.
baseurl: 
url: http://blog.mesguerra.org
github_username: esguerra
remote_theme: yous/whiteglass
plugins:
- jekyll-archives
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
permalink: "/:year/:month/:day/:title/"
paginate_path: "/posts/:num/"
paginate: 10
jekyll-archives:
  enabled:
  - categories
  - tags
  layout: category_archives
  permalinks:
    category: "/categories/:name/"
    tag: "/tags/:name/"
